name: Build API Project

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - develop
      - canary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .Net environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build
